# Generated by Django 4.2.1 on 2023-05-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parentId', models.BigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('meta_title', models.CharField(max_length=50, null=True)),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('author_id', models.BigIntegerField(db_index=True, max_length=20)),
                ('parent_id', models.BigIntegerField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('meta_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(max_length=100)),
                ('published', models.SmallIntegerField(max_length=1)),
                ('createdAt', models.DateTimeField(verbose_name='Create At')),
                ('updatedAt', models.DateTimeField(verbose_name='Update At')),
                ('publishedAt', models.DateTimeField(verbose_name='Published At')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('postId', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('categoryId', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Comment',
            fields=[
                ('post_comment_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField()),
                ('parentId', models.BigIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('published', models.SmallIntegerField(max_length=1)),
                ('createdAt', models.DateTimeField(verbose_name='Created At')),
                ('publishedAt', models.DateTimeField(verbose_name='Published At')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_Meta',
            fields=[
                ('meta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField(unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField(default=True)),
            ],
        ),
    ]
